### ISSUE TITLE
 Incorrect SteamID64 in users API Endpoints

### ISSUE THREAD

**Issue by linventif** [everyday-as/pivity-issues#1305]
### Expected Behavior

res.body: {
  "data": {
    "id": "27eec092-54fd-4c08-9db6-e6c1af3421e2",
    "steamId": 76561198118140425,
    [...]
  }
}

### Actual Behavior

res.body: {
  "data": {
    "id": "27eec092-54fd-4c08-9db6-e6c1af3421e2",
    "steamId": 76561198118140430,
    [...]
  }
}

### Reproduction Steps

```markdown
fetch: https://api.pivity.com/v3/users/27eec092-54fd-4c08-9db6-e6c1af3421e2
```

### Browsers

x

### Example URL

x

### Pivity Marketplace Version

x

### Event ID

x

### Additional Information

Hi,

I've found a bug in your API where the last decimal of the user's Steam ID is rounded in the endpoint /api/v3/users/.

For example, with the user 27eec092-54fd-4c08-9db6-e6c1af3421e2 ([link](https://www.gmodstore.com/users/justplayer) / JustPlayer):

The API returns the Steam ID as 76561198118140430, which is incorrect. The correct Steam ID should be 76561198118140425.

Please look into this issue to ensure the Steam IDs are returned correctly.

Thank you.

Best regards,

Linventif

**Comment by TheodoorP** [comment]
Would you be able to provide some further information on how you're making these requests? I'm unable to replicate your issue:
![image](https://github.com/user-attachments/assets/3153c095-1f51-455d-b273-b39fde79e51d)

I'm assuming you're using a Javascript client to make these requests, is it possible that your client handles the Steam ID as an int32 instead of an int64?

**Comment by linventif** [comment]
> Would you be able to provide some further information on how you're making these requests? I'm unable to replicate your issue:
> ![image](https://github.com/user-attachments/assets/3153c095-1f51-455d-b273-b39fde79e51d)
> 
> I'm assuming you're using a Javascript client to make these requests, is it possible that your client handles the Steam ID as an int32 instead of an int64?

What's ur base url ?

I've just test from my phone and the same problem with me, last 2 digits are 72 not 80.

https://api.pivity.com/v3/me

Test with my token if u want I will delete it in few hours: 19f8a2bb-3937-44ff-8071-31dc9863fbcf|BEoQweVCc0YL0q3uY5nBqHEOddqGHjSldvF7nsde11ccae3c

![Screenshot_2024-08-15-20-00-17-58_927b32dfe2dab93fc1268a64c6a1e8bd.jpg](https://github.com/user-attachments/assets/cbdcf7d1-39f1-48de-9574-2167039bb374)

**Comment by linventif** [comment]
*73 my bad

![Screenshot_2024-08-15-20-03-05-04_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/user-attachments/assets/31c43fd6-cd30-4cb4-843d-e1976cd88beb)

**Comment by TheodoorP** [comment]
I'm still unable to replicate your issue 😅
![image](https://github.com/user-attachments/assets/f9371e62-4f1f-4eb2-b8ac-3684108bc755)

**Comment by linventif** [comment]
Wtf xD
Will test with postman at my return.
I've had this issues with node fetch and  Bruno.

**Comment by linventif** [comment]
Can it be a local caching issue ?
Like the steamid is considered as  number on a caching worker ?

**Comment by TheodoorP** [comment]
I've attempted the same request in Bruno and node fetch, and I get the same results as you do. 

This is due to both using Javascript to deserialize (read) the response, and Javascript reading the steamid as an int32. steamids should be stored in 64 bit integers (known as BigInt in Javascript), but the included json parse function in Javascript does not support BigInt.

Closing this issue as this is a problem with the API client you're using, and not the API. If you need further help on reading the steamid correctly let me know 😄
